# Generated by Django 3.1.10 on 2021-12-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('studentid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=30)),
                ('studentage', models.IntegerField()),
            ],
        ),
    ]
